const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../public/app.js'),'utf8');
const lines=source.split('\n');
let item={direction:'EXPORT · SEA FCL',status:'IN TRANSIT',progress:4,tone:'normal'};
const timeline={innerHTML:''};
const context={shipment:()=>item,$:()=>timeline,steps:['Import only']};
vm.createContext(context);
for(const name of ['renderTimeline','vesselProgressForShipment'])vm.runInContext(lines.find(line=>line.includes('function '+name+'(')),context);
context.renderTimeline();
assert.match(timeline.innerHTML,/Gate-in/);assert.match(timeline.innerHTML,/Loading yard/);
assert.doesNotMatch(timeline.innerHTML,/Import only|Transshipment|Customs/);
assert.match(timeline.innerHTML,/current[^]*Departure/);
assert.equal(context.vesselProgressForShipment(item,'IN_TRANSIT'),.12);
assert.equal(context.vesselProgressForShipment(item,'LOADED'),0);
assert.equal(context.vesselProgressForShipment(item,'ARRIVED'),1);
item.status='ARRIVED';context.renderTimeline();assert.match(timeline.innerHTML,/current[^]*Arrival/);
assert.match(lines.find(line=>line.includes("id:'EXPORT_ARRIVAL'")),/to:1/);
assert.match(lines.find(line=>line.includes('function playSyncedEvent(')),/EXPORT_VESSEL_ARRIVAL'\?1/);
assert.match(lines.find(line=>line.includes("id:'EXPORT_DEPARTURE'")),/to:\.12/);
assert.match(lines.find(line=>line.includes('function playSyncedEvent(')),/EXPORT_SEA_ROUTE'\?\.12/);
assert.match(lines.find(line=>line.includes("id:'EXPORT_LOAD'")),/requiresDocs:true/);
let message='';
Object.assign(context,{state:{animation:null},scenarios:{'EXP-004':[{id:'EXPORT_LOAD'}]},requiredDocuments:{EXPORT_LOAD:['Export Declaration']},toast:value=>message=value,$:()=>({animate:()=>{}})});
const start=source.indexOf('  function runNextEvent(){'),end=source.indexOf('\n  function reset(){',start);
vm.runInContext(source.slice(start,end),context);
item={id:'EXP-004',docs:[['Export Declaration','Pending','pending']]};
context.runNextEvent();assert.match(message,/required document/);assert.equal(context.state.animation,null);
item.docs=[['Export Declaration','Received','ready']];message='';
context.runNextEvent();assert.match(message,/required document/);assert.equal(context.state.animation,null);
console.log('Export UI regressions passed: pending/received declaration blocks loading, distinct timeline, departure stays near origin in demo and synced events.');
